### ISSUE TITLE
Riorganizzazione LG

### ISSUE THREAD

**Issue by ioggstream** [italia/lg-modellointeroperabilita-docs#131]
## Mi aspetto

- delle LG senza le ridondanze causate dal rilascio dei nuovi capitoli

## Strategia

- ove possibile lavorare sui singoli capitoli separatamente
- non sostituire i png/jpg
- ogni capitolo ha il suo gdoc, le modifiche editoriali vengono concordate lì e poi riportate in PR
- le PR che migliorano la leggibilità del documento usano la label:editorial

## Roadmap

- [ ] il capitolo 2 anticipava i contenuti del capitolo 3: le parti ridondanti vanno rimosse #132
- [ ] il lessico del capitolo 1 va rivisto #133
- [x] tutti i diagrammi vanno sostituiti ove possibile da mermaidjs, le immagini restano immutate
- [ ] i commenti ricevuti vanno tracciati sia se integrati sia se ignorati

**Comment by ioggstream** [comment]
stale a valle delle Linee d'indirizzo
