### ISSUE TITLE
Capitolo 2: rimuovere le parti duplicate

### ISSUE THREAD

**Issue by ioggstream** [italia/lg-modellointeroperabilita-docs#132]
## Mi aspetto

- che il §2 non anticipi parti del §3
- che il §3 sia coerente con le indicazioni del §2
- che sia semplificato enfatizzando le parti principali
- che siano gestiti i commenti alla consultazione
- rimandiamo al MODI2021 la discussione di altre tencnologie (graphql, ... )

## Roadmap

- [ ] il concetto di servizio: il paragrafo deve essere così dettagliato o possiamo partire dal §2.1.2?
- [ ] 2.1.2 servizio digitale, API e interfaccia di servizio: anche se da semplificare possiamo considerare la mappatura con la recente letteratura:
   * API: in senso generico uno qualsiasi dei tre aspetti
   * e-service: API instance
   * (manca): API implementation, l'implementazione di un'API che può essere deployata da più parti.
   * interfaccia di servizio: API interface
- [ ] [2.2](https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/bozza/doc/doc_02_cap_02.html#concetti-di-sicurezza) @berez23 proponi pure emendamenti a tutto il capitolo
- [ ] [2.2.3](https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/bozza/doc/doc_02_cap_02.html#protocolli-per-autenticazione-e-autorizzazione) --> migrare in §3 la parte regolatoria
- [ ] [2.2.4](https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/bozza/doc/doc_02_cap_02.html#protocolli-per-integrita-e-confidenzialita) --> migrare in §4 la parte regolatoria che è dettagliata anche in Elenco Algoritmi
- [ ] [2.3](https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/bozza/doc/doc_02_cap_03.html#soap) SOAP spostare le Indicazioni di Utilizzo in §3, vedi commento @lugce-it 
- [ ] [2.4](https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/bozza/doc/doc_02_cap_04.html#rest) REST spostare le Indicazioni di Utilizzo in §3. Rimuovere la discussione sui vari IDL e lasciare solo OAS3. Riportare i dettagli sulla sicurezza in §3.
- [ ] Message broker: recepire commenti. Riportare parte normativa in §3 (se non già presente) e linkarla.
- [ ] Considerazioni comparative: spostare in §3 tutta la parte normativa. questa contiene il principio contract-first/api-first alla fine del capitolo. Andrebbe tolto e messo ben in evidenza in §3.

**Comment by ioggstream** [comment]
PR stantia
